name: CI Build
on:
  pull_request:
    branches: 
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directories:
          - "./Marketplace/SterlingOMS"

    steps:
      - name: Linting ${{ matrix.directories }}
        id: linting
        uses: venura9/arm-ttk@master
        with: 
          path: ${{ matrix.directories }}

      - name: Test Results for ${{ matrix.directories }}
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.linting.outputs.results)) }}"
          