name: CI Build
on:
  pull_request:
    branches: 
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directories:
          - "./Networking/base-vnet.json"
          - "./Networking/bastion.json"
          - "./Compute/ubuntu-vm-pwd.json"
          - "./Compute/dev-vm.json"
          - "./Networking/subnet.json"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linting ${{ matrix.directories }}
        id: linting
        uses: microsoft/action-armttk@v1
        with: 
          workdir: ${{ matrix.directories }}
          github_token: ${{ secrets.TOKEN }}
          