name: CI Build
on:
  pull_request:
    branches: 
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directories:
          - "./Marketplace/SterlingOMS"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linting ${{ matrix.directories }}
        id: linting
        uses: microsoft/action-armttk/.github/workflows/arm-ttk@v1
        with: 
          workdir: ${{ matrix.directories }}
          github_token: ${{ secrets.TOKEN }}
          